"""added nodes table

Revision ID: 0a40f2436fbf
Revises: f819031f8260
Create Date: 2020-03-09 10:49:54.630958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a40f2436fbf'
down_revision = 'f819031f8260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RegisteredNodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_node_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_node_id')
    )
    op.drop_index('ix_User_email', table_name='User')
    op.drop_index('ix_User_username', table_name='User')
    op.create_index(op.f('ix_UpdateAggregator_errorRate'), 'UpdateAggregator', ['errorRate'], unique=False)
    op.create_index(op.f('ix_UpdateAggregator_postCode'), 'UpdateAggregator', ['postCode'], unique=False)
    op.create_index(op.f('ix_UpdateAggregator_supportCode'), 'UpdateAggregator', ['supportCode'], unique=False)
    op.create_index(op.f('ix_UpdateAggregator_weeklyCalls'), 'UpdateAggregator', ['weeklyCalls'], unique=False)
    op.create_index(op.f('ix_UpdateAggregator_weeklySteps'), 'UpdateAggregator', ['weeklySteps'], unique=False)
    op.create_index(op.f('ix_UpdateAggregator_wellBeingScore'), 'UpdateAggregator', ['wellBeingScore'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UpdateAggregator_wellBeingScore'), table_name='UpdateAggregator')
    op.drop_index(op.f('ix_UpdateAggregator_weeklySteps'), table_name='UpdateAggregator')
    op.drop_index(op.f('ix_UpdateAggregator_weeklyCalls'), table_name='UpdateAggregator')
    op.drop_index(op.f('ix_UpdateAggregator_supportCode'), table_name='UpdateAggregator')
    op.drop_index(op.f('ix_UpdateAggregator_postCode'), table_name='UpdateAggregator')
    op.drop_index(op.f('ix_UpdateAggregator_errorRate'), table_name='UpdateAggregator')
    op.create_table('MainData',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('supportCode', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('wellBeingScore', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('weeklySteps', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('weeklyCalls', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('errorRate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('postCode', mysql.VARCHAR(length=10), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('User',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), server_default=sa.text("''"), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('user_type', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_User_username', 'User', ['username'], unique=True)
    op.create_index('ix_User_email', 'User', ['email'], unique=True)
    op.drop_table('RegisteredNodes')
    # ### end Alembic commands ###
