"""add uploaded ml models table

Revision ID: 2d58111198cd
Revises: 0a40f2436fbf
Create Date: 2020-04-21 19:29:27.593399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d58111198cd'
down_revision = '0a40f2436fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MLModelsMeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('json_summary', sa.JSON(), nullable=True),
    sa.Column('deployed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MLModelsMeta_filename'), 'MLModelsMeta', ['filename'], unique=True)
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_index(op.f('ix_MLModelsMeta_filename'), table_name='MLModelsMeta')
    op.drop_table('MLModelsMeta')
    # ### end Alembic commands ###
