"""user types are now booleans

Revision ID: f819031f8260
Revises: ae31f81e2a0e
Create Date: 2020-03-05 01:49:29.669899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f819031f8260'
down_revision = 'ae31f81e2a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_MainData_errorRate', table_name='MainData')
    op.drop_index('ix_MainData_postCode', table_name='MainData')
    op.drop_index('ix_MainData_supportCode', table_name='MainData')
    op.drop_index('ix_MainData_weeklyCalls', table_name='MainData')
    op.drop_index('ix_MainData_weeklySteps', table_name='MainData')
    op.drop_index('ix_MainData_wellBeingScore', table_name='MainData')
    op.drop_index('ix_UpdateAggregator_errorRate', table_name='UpdateAggregator')
    op.drop_index('ix_UpdateAggregator_postCode', table_name='UpdateAggregator')
    op.drop_index('ix_UpdateAggregator_supportCode', table_name='UpdateAggregator')
    op.drop_index('ix_UpdateAggregator_weeklyCalls', table_name='UpdateAggregator')
    op.drop_index('ix_UpdateAggregator_weeklySteps', table_name='UpdateAggregator')
    op.drop_index('ix_UpdateAggregator_wellBeingScore', table_name='UpdateAggregator')
    op.drop_index('ix_User_user_type', table_name='User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_User_user_type', 'User', ['user_type'], unique=False)
    op.create_table('UpdateAggregator',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('supportCode', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('wellBeingScore', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('weeklySteps', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('weeklyCalls', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('errorRate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('postCode', mysql.VARCHAR(length=10), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_UpdateAggregator_wellBeingScore', 'UpdateAggregator', ['wellBeingScore'], unique=False)
    op.create_index('ix_UpdateAggregator_weeklySteps', 'UpdateAggregator', ['weeklySteps'], unique=False)
    op.create_index('ix_UpdateAggregator_weeklyCalls', 'UpdateAggregator', ['weeklyCalls'], unique=False)
    op.create_index('ix_UpdateAggregator_supportCode', 'UpdateAggregator', ['supportCode'], unique=False)
    op.create_index('ix_UpdateAggregator_postCode', 'UpdateAggregator', ['postCode'], unique=False)
    op.create_index('ix_UpdateAggregator_errorRate', 'UpdateAggregator', ['errorRate'], unique=False)
    op.create_table('MainData',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('supportCode', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('wellBeingScore', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('weeklySteps', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('weeklyCalls', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('errorRate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('postCode', mysql.VARCHAR(length=10), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_MainData_wellBeingScore', 'MainData', ['wellBeingScore'], unique=False)
    op.create_index('ix_MainData_weeklySteps', 'MainData', ['weeklySteps'], unique=False)
    op.create_index('ix_MainData_weeklyCalls', 'MainData', ['weeklyCalls'], unique=False)
    op.create_index('ix_MainData_supportCode', 'MainData', ['supportCode'], unique=False)
    op.create_index('ix_MainData_postCode', 'MainData', ['postCode'], unique=False)
    op.create_index('ix_MainData_errorRate', 'MainData', ['errorRate'], unique=False)
    # ### end Alembic commands ###
